
SMODS.Challenge{
  key = "Investstream",
  loc_txt = {
    name = "Neuro stocks",
    text = {
      "Start with 8 VedalAI Stocks,",
      "3 of which are negative.",
      "Earn no money at end of round"
    }},
  rules = {
        custom = {
            {id = "no_extra_hand_money"},
            {id = "no_interest"},
            {id = "no_reward"}
        }},
  restrictions = {
        banned_cards = {
            { id = 'v_seed_money' },
            { id = 'v_money_tree' },
            { id = 'j_to_the_moon' },
            { id = 'j_rocket' },
            { id = 'j_golden' },
            { id = 'j_satellite' },
            { id = 'j_shoomimi' },
            { id = 'j_stocks' },
            { id = 'j_corpa' },
        }
    },
  deck = {
    type = 'Challenge Deck'
  },
  jokers = {
    {id = "j_stocks"},{id = "j_stocks"},{id = "j_stocks"},{id = "j_stocks"},{id = "j_stocks"},{id = "j_stocks",edition = "negative"},{id = "j_stocks",edition = "negative"},{id = "j_stocks",edition = "negative"},
}}
SMODS.Challenge{
  key = "Plush_lover",
  loc_txt = {
    name = "Plushie collection",
  },
  rules = {
        modifiers = {
          {id = "hands", value = 3},
          {id = "discards", value = 3},
          {id = "joker_slots", value = 4}
        }},
  deck = {
    type = 'Challenge Deck'
  },
  jokers = {
    {id = "j_plush", eternal = true},{id = "j_sispace", eternal = true},{id = "j_harpoon",  eternal = true}
}}
SMODS.Challenge{
  key = "heartheartheartheartheartheartheart",
  loc_txt = {
    name = "heartheartheartheartheartheart",
  },
  jokers = {
    {id = "j_lucy", eternal = true},{id = "j_3heart", eternal = true}
  },
  deck = {
    type = 'Challenge Deck',
        cards = {
            { s = 'H', r = 'A' },
            { s = 'H', r = 'A' },
            { s = 'H', r = 'A' },
            { s = 'H', r = 'A' },
            { s = 'H', r = 'K' },
            { s = 'H', r = 'K' },
            { s = 'H', r = 'K' },
            { s = 'H', r = 'K' },
            { s = 'H', r = 'Q' },
            { s = 'H', r = 'Q' },
            { s = 'H', r = 'Q' },
            { s = 'H', r = 'Q' },
            { s = 'H', r = 'J' },
            { s = 'H', r = 'J' },
            { s = 'H', r = 'J' },
            { s = 'H', r = 'J' },
            { s = 'H', r = 'T' },
            { s = 'H', r = 'T' },
            { s = 'H', r = 'T' },
            { s = 'H', r = 'T' },
            { s = 'H', r = '9' },
            { s = 'H', r = '9' },
            { s = 'H', r = '9' },
            { s = 'H', r = '9' },
            { s = 'H', r = '8' },
            { s = 'H', r = '8' },
            { s = 'H', r = '8' },
            { s = 'H', r = '8' },
            { s = 'H', r = '7' },
            { s = 'H', r = '7' },
            { s = 'H', r = '7' },
            { s = 'H', r = '7' },
            { s = 'H', r = '6' },
            { s = 'H', r = '6' },
            { s = 'H', r = '6' },
            { s = 'H', r = '6' },
            { s = 'H', r = '5' },
            { s = 'H', r = '5' },
            { s = 'H', r = '5' },
            { s = 'H', r = '5' },
            { s = 'H', r = '4' },
            { s = 'H', r = '4' },
            { s = 'H', r = '4' },
            { s = 'H', r = '4' },
            { s = 'H', r = '3' },
            { s = 'H', r = '3' },
            { s = 'H', r = '3' },
            { s = 'H', r = '3' },
            { s = 'H', r = '2' },
            { s = 'H', r = '2' },
            { s = 'H', r = '2' },
            { s = 'H', r = '2' },
        }
    },
   restrictions = {
        banned_cards = {
            { id = 'c_lovers' },
            { id = 'c_moon' },
            { id = 'c_star' },
            { id = 'c_world' },
            { id = 'c_sigil' },
            { id = 'c_familiar' },
            { id = 'c_grim' },
            { id = 'c_incantation' },
            { id = 'j_smeared' },
            { id = 'j_allin' },
            { id = 'j_jokr' },
            { id = 'j_Glorp' },
            { id = 'j_certificate' },
             { id = 'v_magic_trick' },
            { id = 'v_illusion' },
            { id = 'p_standard_normal_1', ids = {
                'p_standard_normal_1', 'p_standard_normal_2',
                'p_standard_normal_3', 'p_standard_normal_4',
                'p_standard_jumbo_1', 'p_standard_jumbo_2',
                'p_standard_mega_1', 'p_standard_mega_2' }
            }, 
        },
        banned_tags = {
            { id = 'tag_standard' },
        }
    }
  
}
SMODS.Challenge{
  key = "invasion",
  loc_txt = {
    name = "Invasion",
  },
  jokers = {
    {id = "j_Glorp", eternal = true, edition = "negative"},{id = "j_Glorp", eternal = true, edition = "negative"},{id = "j_envy", eternal = true}
  },
  deck = {
    type = 'Challenge Deck',
        cards = {
            
        }
    },
   restrictions = {
        banned_cards = {
            { id = 'c_lovers' },
            { id = 'c_moon' },
            { id = 'c_star' },
            { id = 'c_world' },
            { id = 'c_sun' },
            { id = 'c_magician' },
            { id = 'c_empress' },
            { id = 'c_heirophant' },
            { id = 'c_chariot' },
            { id = 'c_justice' },
            { id = 'c_devil' },
            { id = 'c_tower' },
            { id = 'c_twins' },
            { id = 'c_donation' },
            { id = 'c_sigil' },
            { id = 'c_familiar' },
            { id = 'c_grim' },
            { id = 'c_incantation' },
            { id = 'j_jokr' },
            { id = 'j_Glorp' },
            { id = 'j_marble' },
            { id = 'j_vampire' },
            { id = 'j_midas_mask' },
            { id = 'j_pipes' },
            { id = 'j_allin' },
            { id = 'j_cavestream' },
            { id = 'j_certificate' },
             { id = 'v_magic_trick' },
            { id = 'v_illusion' },
            { id = 'p_standard_normal_1', ids = {
                'p_standard_normal_1', 'p_standard_normal_2',
                'p_standard_normal_3', 'p_standard_normal_4',
                'p_standard_jumbo_1', 'p_standard_jumbo_2',
                'p_standard_mega_1', 'p_standard_mega_2' }
            },
        },
        banned_tags = {
            { id = 'tag_standard' },
        }
    }
  
}
SMODS.Challenge{
  key = "SwarmAddict",
  loc_txt = {
    name = "Swarm Addict"
  },
  deck = {
    type = 'Challenge Deck'
  },
  restrictions = {
        banned_cards = {
  { id = 'j_joker' },
  { id = 'j_greedy_joker' },
  { id = 'j_lusty_joker' },
  { id = 'j_wrathful_joker' },
  { id = 'j_gluttenous_joker' },
  { id = 'j_zany' },
  { id = 'j_mad' },
  { id = "j_jolly"},
  { id = 'j_crazy' },
  { id = 'j_droll' },
  { id = 'j_sly' },
  { id = 'j_wily' },
  { id = 'j_clever' },
  { id = 'j_devious' },
  { id = 'j_crafty' },
  { id = 'j_half' },
  { id = 'j_stencil' },
  { id = 'j_four_fingers' },
  { id = 'j_mime' },
  { id = 'j_credit_card' },
  { id = 'j_ceremonial' },
  { id = 'j_banner' },
  { id = 'j_mystic_summit' },
  { id = 'j_marble' },
  { id = 'j_loyalty_card' },
  { id = 'j_8_ball' },
  { id = 'j_misprint' },
  { id = 'j_dusk' },
  { id = 'j_raised_fist' },
  { id = 'j_chaos' },
  { id = 'j_fibonacci' },
  { id = 'j_steel_joker' },
  { id = 'j_scary_face' },
  { id = 'j_abstract' },
  { id = 'j_delayed_grat' },
  { id = 'j_hack' },
  { id = 'j_pareidolia' },
  { id = 'j_gros_michel' },
  { id = 'j_even_steven' },
  { id = 'j_odd_todd' },
  { id = 'j_scholar' },
  { id = 'j_business' },
  { id = 'j_supernova' },
  { id = 'j_ride_the_bus' },
  { id = 'j_space' },
  { id = 'j_egg' },
  { id = 'j_burglar' },
  { id = 'j_blackboard' },
  { id = 'j_runner' },
  { id = 'j_ice_cream' },
  { id = 'j_dna' },
  { id = 'j_splash' },
  { id = 'j_blue_joker' },
  { id = 'j_sixth_sense' },
  { id = 'j_constellation' },
  { id = 'j_hiker' },
  { id = 'j_faceless' },
  { id = 'j_green_joker' },
  { id = 'j_superposition' },
  { id = 'j_todo_list' },
  { id = 'j_cavendish' },
  { id = 'j_card_sharp' },
  { id = 'j_red_card' },
  { id = 'j_madness' },
  { id = 'j_square' },
  { id = 'j_seance' },
  { id = 'j_riff_raff' },
  { id = 'j_vampire' },
  { id = 'j_shortcut' },
  { id = 'j_hologram' },
  { id = 'j_vagabond' },
  { id = 'j_baron' },
  { id = 'j_cloud_9' },
  { id = 'j_rocket' },
  { id = 'j_obelisk' },
  { id = 'j_midas_mask' },
  { id = 'j_luchador' },
  { id = 'j_photograph' },
  { id = 'j_gift' },
  { id = 'j_turtle_bean' },
  { id = 'j_erosion' },
  { id = 'j_reserved_parking' },
  { id = 'j_mail' },
  { id = 'j_to_the_moon' },
  { id = 'j_hallucination' },
  { id = 'j_fortune_teller' },
  { id = 'j_juggler' },
  { id = 'j_drunkard' },
  { id = 'j_stone' },
  { id = 'j_golden' },
  { id = 'j_lucky_cat' },
  { id = 'j_baseball' },
  { id = 'j_bull' },
  { id = 'j_diet_cola' },
  { id = 'j_trading' },
  { id = 'j_flash' },
  { id = 'j_popcorn' },
  { id = 'j_trousers' },
  { id = 'j_ancient' },
  { id = 'j_ramen' },
  { id = 'j_walkie_talkie' },
  { id = 'j_selzer' },
  { id = 'j_castle' },
  { id = 'j_smiley' },
  { id = 'j_campfire' },
  { id = 'j_ticket' },
  { id = 'j_mr_bones' },
  { id = 'j_acrobat' },
  { id = 'j_sock_and_buskin' },
  { id = 'j_swashbuckler' },
  { id = 'j_troubadour' },
  { id = 'j_certificate' },
  { id = 'j_smeared' },
  { id = 'j_throwback' },
  { id = 'j_hanging_chad' },
  { id = 'j_rough_gem' },
  { id = 'j_bloodstone' },
  { id = 'j_arrowhead' },
  { id = 'j_onyx_agate' },
  { id = 'j_glass' },
  { id = 'j_ring_master' },
  { id = 'j_flower_pot' },
  { id = 'j_blueprint' },
  { id = 'j_wee' },
  { id = 'j_merry_andy' },
  { id = 'j_oops' },
  { id = 'j_idol' },
  { id = 'j_seeing_double' },
  { id = 'j_matador' },
  { id = 'j_hit_the_road' },
  { id = 'j_duo' },
  { id = 'j_trio' },
  { id = 'j_family' },
  { id = 'j_order' },
  { id = 'j_tribe' },
  { id = 'j_stuntman' },
  { id = 'j_invisible' },
  { id = 'j_brainstorm' },
  { id = 'j_satellite' },
  { id = 'j_shoot_the_moon' },
  { id = 'j_drivers_license' },
  { id = 'j_cartomancer' },
  { id = 'j_astronomer' },
  { id = 'j_burnt' },
  { id = 'j_bootstraps' },
  { id = 'j_caino' },
  { id = 'j_triboulet' },
  { id = 'j_yorick' },
  { id = 'j_chicot' },
  { id = 'j_perkeo' }
        },
  }
}
SMODS.Challenge{
  key = "xdx|3",
  loc_txt  = { name = "xdx |"},
  deck = { type = "Challenge Deck"},
  jokers = {
    {id = "j_xdx|", eternal = true},{id = "j_xdx|", eternal = true},{id = "j_xdx|", eternal = true},{id = "j_xdx|", eternal = true},{id = "j_xdx|", eternal = true}
  }
}
